# Generated by Django 5.0.6 on 2024-07-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_userrecommendationpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrecommendationpreference",
            name="author_weight",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userrecommendationpreference",
            name="genre_weight",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userrecommendationpreference",
            name="similar_user_weight",
            field=models.FloatField(default=0),
        ),
    ]
